title: Loïc Kreienbühl
description: Personal website, resume, and projects
url: "https://loickreienbuhl.github.io"
baseurl: ""

theme: minima

plugins:
  - jekyll-seo-tag

header_pages:
  - resume.md
  - projects.md

markdown: kramdown
